export const CARRIER_CATALOG = [
  {
    id: "hartford",
    name: "The Hartford",
    logoMark: "HF",
    logoColor: "#1a3a6b",
    category: "Carrier",
    description: "Workers' comp, general liability, umbrella - top-rated A+ carrier.",
    policyTypes: ["workers", "liability", "umbrella"],
    amRating: "A+",
    capabilities: ["policy_sync", "coi_verify", "renewal_alerts"],
    popular: true,
  },
  {
    id: "travelers",
    name: "Travelers",
    logoMark: "TR",
    logoColor: "#c8102e",
    category: "Carrier",
    description: "Commercial property, auto, and liability coverage nationwide.",
    policyTypes: ["property", "auto", "liability"],
    amRating: "A++",
    capabilities: ["policy_sync", "coi_verify"],
    popular: true,
  },
  {
    id: "next",
    name: "NEXT Insurance",
    logoMark: "NX",
    logoColor: "#0070f3",
    category: "Carrier",
    description: "Digital-first carrier built for small businesses and contractors.",
    policyTypes: ["liability", "workers", "auto"],
    amRating: "A (Excellent)",
    capabilities: ["policy_sync", "coi_verify", "instant_coi", "renewal_alerts"],
    popular: true,
  },
  {
    id: "hiscox",
    name: "Hiscox",
    logoMark: "HX",
    logoColor: "#6b2d8b",
    category: "Carrier",
    description: "Specialty liability and umbrella coverage for contractors.",
    policyTypes: ["liability", "umbrella"],
    amRating: "A (Excellent)",
    capabilities: ["policy_sync", "coi_verify"],
    popular: false,
  },
  {
    id: "progressive",
    name: "Progressive Commercial",
    logoMark: "PC",
    logoColor: "#0066cc",
    category: "Carrier",
    description: "Commercial auto and fleet coverage for contractors.",
    policyTypes: ["auto"],
    amRating: "A+ (Superior)",
    capabilities: ["policy_sync", "renewal_alerts"],
    popular: false,
  },
  {
    id: "statefund",
    name: "StateFund West",
    logoMark: "SF",
    logoColor: "#2d6a4f",
    category: "Carrier",
    description: "Workers' compensation specialist for western states.",
    policyTypes: ["workers"],
    amRating: "A (Excellent)",
    capabilities: ["policy_sync", "coi_verify"],
    popular: false,
  },
  {
    id: "acme",
    name: "Acme Mutual",
    logoMark: "AM",
    logoColor: "#7c3aed",
    category: "Carrier",
    description: "General liability and commercial property for trade contractors.",
    policyTypes: ["liability", "property"],
    amRating: "A (Excellent)",
    capabilities: ["policy_sync"],
    popular: false,
  },
  {
    id: "nationwide",
    name: "Nationwide",
    logoMark: "NW",
    logoColor: "#1f4e8c",
    category: "Carrier",
    description: "Full commercial lines including umbrella and inland marine.",
    policyTypes: ["liability", "umbrella", "property", "auto"],
    amRating: "A+ (Superior)",
    capabilities: ["policy_sync", "coi_verify", "renewal_alerts"],
    popular: false,
  },
  {
    id: "libertymutual",
    name: "Liberty Mutual",
    logoMark: "LM",
    logoColor: "#c8a200",
    category: "Carrier",
    description: "Commercial lines coverage with strong contractor programs.",
    policyTypes: ["liability", "workers", "property"],
    amRating: "A (Excellent)",
    capabilities: ["policy_sync", "coi_verify"],
    popular: false,
  },
  {
    id: "acord",
    name: "ACORD Connect",
    logoMark: "AC",
    logoColor: "#334155",
    category: "Platform",
    description: "Standardized ACORD form exchange - pull COIs and dec pages directly from ACORD-compliant carriers.",
    policyTypes: ["liability", "workers", "property", "auto", "umbrella"],
    amRating: null,
    capabilities: ["coi_verify", "form_pull"],
    popular: true,
  },
  {
    id: "ams360",
    name: "Applied Epic / AMS360",
    logoMark: "AE",
    logoColor: "#e07b00",
    category: "Agency System",
    description: "Sync policies from your insurance agent's management system.",
    policyTypes: ["liability", "workers", "property", "auto", "umbrella"],
    amRating: null,
    capabilities: ["policy_sync", "renewal_alerts"],
    popular: false,
  },
  {
    id: "ezlynx",
    name: "EZLynx",
    logoMark: "EZ",
    logoColor: "#0ea5e9",
    category: "Agency System",
    description: "Agent rating and management platform - pull live policy data.",
    policyTypes: ["liability", "workers", "property", "auto"],
    amRating: null,
    capabilities: ["policy_sync"],
    popular: false,
  },
];
