/**
 * Initial mock data for SubShield.
 * This is intentionally structured like a production data model while still
 * being persisted locally for this frontend-only repository.
 */

function isoDaysAgo(days) {
  const date = new Date();
  date.setDate(date.getDate() - days);
  return date.toISOString();
}

function isoDaysFromNow(days) {
  const date = new Date();
  date.setDate(date.getDate() + days);
  return date.toISOString().slice(0, 10);
}

const COMPANY_ID = "subshield-tile-co";

export const initialData = {
  company: {
    id: COMPANY_ID,
    name: "SubShield Tile Co.",
    tradeType: "Tile & stone installation",
    state: "TX",
    revenueRange: "$1M-$5M",
    employees: "11-25",
    contactEmail: "owner@subshieldtile.com",
  },

  policies: [
    {
      id: "wc",
      companyId: COMPANY_ID,
      policyType: "workers",
      type: "workers",
      name: "Workers' Compensation",
      carrier: "StateFund West",
      policyNumber: "WC-90183321",
      premiumAmount: 3210,
      premium: 3210,
      premiumFrequency: "annual",
      effectiveDate: isoDaysFromNow(-361),
      expirationDate: isoDaysFromNow(4),
      renewalDate: isoDaysFromNow(4),
      expires: isoDaysFromNow(4),
      daysRemaining: 4,
      coverageLimits: "Statutory / $1M employer liability",
      limit: "Statutory / $1M employer liability",
      brokerId: "brk-lighthouse",
      documents: ["WC certificate", "Waiver of Subrogation"],
      status: "critical",
      statusNote: "Critical. Renew before sending new COI packages.",
      savingsStatus: "available",
      lastQuotedAt: isoDaysAgo(220),
      createdAt: isoDaysAgo(365),
      updatedAt: isoDaysAgo(2),
    },
    {
      id: "gl",
      companyId: COMPANY_ID,
      policyType: "liability",
      type: "liability",
      name: "General Liability",
      carrier: "Acme Mutual",
      policyNumber: "GL-44827193",
      premiumAmount: 1840,
      premium: 1840,
      premiumFrequency: "annual",
      effectiveDate: isoDaysFromNow(-320),
      expirationDate: isoDaysFromNow(45),
      renewalDate: isoDaysFromNow(45),
      expires: isoDaysFromNow(45),
      daysRemaining: 45,
      coverageLimits: "$2M aggregate / $1M occurrence",
      limit: "$2M aggregate / $1M occurrence",
      brokerId: "brk-lighthouse",
      documents: ["GL certificate", "Additional Insured", "Waiver of Subrogation"],
      status: "active",
      statusNote: "Inside the renewal planning window.",
      savingsStatus: "monitoring",
      lastQuotedAt: isoDaysAgo(160),
      createdAt: isoDaysAgo(365),
      updatedAt: isoDaysAgo(5),
    },
    {
      id: "auto",
      companyId: COMPANY_ID,
      policyType: "auto",
      type: "auto",
      name: "Commercial Auto",
      carrier: "Progressive Commercial",
      policyNumber: "CA-55120984",
      premiumAmount: 2460,
      premium: 2460,
      premiumFrequency: "annual",
      effectiveDate: isoDaysFromNow(-245),
      expirationDate: isoDaysFromNow(120),
      renewalDate: isoDaysFromNow(120),
      expires: isoDaysFromNow(120),
      daysRemaining: 120,
      coverageLimits: "$1M combined single limit",
      limit: "$1M combined single limit",
      brokerId: "brk-lighthouse",
      documents: ["Auto certificate", "Additional Insured"],
      status: "active",
      statusNote: "Active and ready for routing.",
      savingsStatus: "available",
      lastQuotedAt: isoDaysAgo(350),
      createdAt: isoDaysAgo(365),
      updatedAt: isoDaysAgo(7),
    },
    {
      id: "umbrella",
      companyId: COMPANY_ID,
      policyType: "umbrella",
      type: "umbrella",
      name: "Umbrella / Excess Liability",
      carrier: "Hiscox Insurance Co.",
      policyNumber: "UM-7740921",
      premiumAmount: 980,
      premium: 980,
      premiumFrequency: "annual",
      effectiveDate: isoDaysFromNow(-42),
      expirationDate: isoDaysFromNow(318),
      renewalDate: isoDaysFromNow(318),
      expires: isoDaysFromNow(318),
      daysRemaining: 318,
      coverageLimits: "$2M excess liability",
      limit: "$2M excess liability",
      brokerId: "brk-lighthouse",
      documents: ["Umbrella certificate"],
      status: "active",
      statusNote: "Original umbrella certificate verified.",
      savingsStatus: "monitoring",
      lastQuotedAt: isoDaysAgo(40),
      createdAt: isoDaysAgo(42),
      updatedAt: isoDaysAgo(2),
    },
    {
      id: "license",
      companyId: COMPANY_ID,
      policyType: "license",
      type: "license",
      name: "Trade License",
      carrier: "TX Dept. of Licensing",
      policyNumber: "TL-TILE-0099821",
      premiumAmount: 295,
      premium: 295,
      premiumFrequency: "annual",
      effectiveDate: isoDaysFromNow(-305),
      expirationDate: isoDaysFromNow(60),
      renewalDate: isoDaysFromNow(60),
      expires: isoDaysFromNow(60),
      daysRemaining: 60,
      coverageLimits: "Tile contractor license",
      limit: "Tile contractor license",
      brokerId: null,
      documents: ["Trade license", "State registration"],
      status: "active",
      statusNote: "Current license on file.",
      savingsStatus: "not_applicable",
      lastQuotedAt: null,
      createdAt: isoDaysAgo(365),
      updatedAt: isoDaysAgo(10),
    },
  ],

  contractors: [
    {
      id: "turner",
      name: "Turner Construction",
      initials: "TC",
      contact: "Sarah Chen",
      email: "bids@turner.com",
      phone: "(212) 555-0143",
      delivery: "TrustLayer portal + email copy",
      holder: "Turner Construction Company\n375 Hudson Street\nNew York, NY 10014",
      requirements:
        "Requires $2M umbrella and primary non-contributory wording on GL.",
      projects: ["Downtown Marriott Remodel", "Westside School District"],
      notes: "Prefers certificate holder exactly as legal entity above.",
      portalInstructions: "Upload to TrustLayer, then email compliance copy.",
      pastSends: [
        {
          id: "send-turner-1",
          project: "Downtown Marriott Remodel",
          sentAt: isoDaysAgo(8),
          status: "delivered",
        },
      ],
    },
    {
      id: "suffolk",
      name: "Suffolk",
      initials: "SU",
      contact: "Marcus Patel",
      email: "compliance@suffolk.com",
      phone: "(617) 555-0112",
      delivery: "Compliance inbox",
      holder: "Suffolk Construction Company, Inc.\n65 Allerton Street\nBoston, MA 02119",
      requirements:
        "30-day cancellation notice required. Include Waiver of Subrogation when available.",
      projects: ["Seaport Tower Phase II"],
      notes: "Ask for updated wording before each send.",
      portalInstructions: "",
      pastSends: [],
    },
    {
      id: "dpr",
      name: "DPR Construction",
      initials: "DP",
      contact: "Lena Okafor",
      email: "coi@dpr.com",
      phone: "(650) 555-0136",
      delivery: "myCOI inbox",
      holder: "DPR Construction\n1450 Veterans Blvd\nRedwood City, CA 94063",
      requirements: "Standard verified COI package accepted.",
      projects: ["Genentech Lab Buildout"],
      notes: "",
      portalInstructions: "Send to myCOI + cc project team.",
      pastSends: [],
    },
  ],

  brokers: [
    {
      id: "brk-lighthouse",
      companyId: COMPANY_ID,
      name: "Avery Brooks",
      company: "Lighthouse Construction Risk",
      email: "avery@lighthouse-risk.com",
      phone: "(512) 555-0182",
      policyTypes: ["workers", "liability", "auto", "umbrella"],
      notes: "Primary broker for renewals and certificate changes.",
    },
  ],

  partners: [
    {
      id: "partner-next",
      name: "NEXT Insurance",
      type: "carrier",
      statesServed: ["TX", "CA", "AZ", "NV", "CO"],
      policyTypes: ["liability", "workers", "auto"],
      tradeTypes: ["tile", "drywall", "electrical", "plumbing"],
      contactMethod: "api",
      commissionModel: "referral_fee",
      active: true,
    },
    {
      id: "partner-hartford",
      name: "The Hartford Commercial",
      type: "carrier",
      statesServed: ["TX", "FL", "GA", "NC", "SC"],
      policyTypes: ["workers", "liability", "umbrella"],
      tradeTypes: ["tile", "roofing", "framing"],
      contactMethod: "email",
      commissionModel: "lead_fee",
      active: true,
    },
    {
      id: "partner-summit-broker",
      name: "Summit Trade Insurance Brokers",
      type: "broker",
      statesServed: ["TX", "OK", "LA"],
      policyTypes: ["workers", "auto", "umbrella", "bonding"],
      tradeTypes: ["tile", "hvac", "earthwork"],
      contactMethod: "email",
      commissionModel: "commission_share",
      active: true,
    },
  ],

  savingsOpportunities: [
    {
      id: "sav-wc",
      companyId: COMPANY_ID,
      policyId: "wc",
      policyType: "workers",
      currentCarrier: "StateFund West",
      currentPremium: 3210,
      estimatedSavings: 540,
      renewalDate: isoDaysFromNow(4),
      status: "available",
      partnerId: "partner-hartford",
      createdAt: isoDaysAgo(2),
      updatedAt: isoDaysAgo(0),
      notes: "Upcoming renewal + older quote history.",
    },
    {
      id: "sav-auto",
      companyId: COMPANY_ID,
      policyId: "auto",
      policyType: "auto",
      currentCarrier: "Progressive Commercial",
      currentPremium: 2460,
      estimatedSavings: 360,
      renewalDate: isoDaysFromNow(120),
      status: "available",
      partnerId: "partner-next",
      createdAt: isoDaysAgo(1),
      updatedAt: isoDaysAgo(0),
      notes: "Commercial auto rates are volatile in your trade category.",
    },
  ],

  quoteRequests: [
    {
      id: "qr-1",
      companyId: COMPANY_ID,
      policyId: "wc",
      partnerId: "partner-hartford",
      brokerId: null,
      requestedBy: "owner",
      routeType: "partner",
      businessInfo: {
        companyName: "SubShield Tile Co.",
        tradeType: "Tile & stone installation",
        state: "TX",
        revenueRange: "$1M-$5M",
        employees: "11-25",
      },
      currentCoverageInfo: {
        currentCarrier: "StateFund West",
        currentPremium: 3210,
        renewalDate: isoDaysFromNow(4),
      },
      status: "sent_to_partner",
      submittedAt: isoDaysAgo(1),
      respondedAt: null,
      notes: "Requested workers comp review before renewal.",
    },
  ],

  coiSends: [
    {
      id: "coi-1",
      contractorId: "turner",
      project: "Downtown Marriott Remodel",
      sentAt: isoDaysAgo(8),
      docCount: 8,
      email: "bids@turner.com",
      status: "delivered",
    },
  ],

  preferences: {
    alerts: true,
    routing: true,
    autoshop: false,
  },

  activity: [
    {
      id: "a1",
      title: "Workers' Comp is critical",
      body: "Renewal in 4 days. Review current policy and quote options.",
      time: "Today",
      createdAt: isoDaysAgo(0),
    },
    {
      id: "a2",
      title: "Quote request sent",
      body: "Workers' Compensation routed to The Hartford Commercial partner intake.",
      time: "Yesterday",
      createdAt: isoDaysAgo(1),
    },
    {
      id: "a3",
      title: "COI package routed",
      body: "Turner Construction - Downtown Marriott Remodel - 8 verified files.",
      time: "8 days ago",
      createdAt: isoDaysAgo(8),
    },
    {
      id: "a4",
      title: "Savings opportunity detected",
      body: "Commercial Auto may save $360/yr before next renewal cycle.",
      time: "12 days ago",
      createdAt: isoDaysAgo(12),
    },
  ],
};
